name: miloo_mobile
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.16 # Helps to render SVG files
  signalr_netcore: ^1.4.0 # A Flutter plugin for ASP.NET Core SignalR
  provider: ^6.1.2 # State Management Library for Flutter Applications
  pinput: ^5.0.0 # A Flutter package for pin input field
  shimmer: ^3.0.0 # A package provides an easy way to add shimmer effect in Flutter project
  image_picker: ^1.1.2 # A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera
  http: ^1.2.2 # A composable, multi-platform, Future-based API for HTTP requests
  form_field_validator: ^1.1.0 # A Flutter package for form field validation
  drop_down_list: ^2.0.0 # A Flutter package for dropdown list
  cached_network_image: ^3.3.0 # A flutter library to show images from the internet and keep them in the cache directory
  flutter_cache_manager: ^3.3.0
  flutter_secure_storage: ^9.2.3 # A flutter library to saved user token  
  jwt_decoder: ^2.0.1 # A flutter library to decode JWT tokens
  shared_preferences: ^2.3.5 # A Flutter plugin for reading and writing simple key-value pairs
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# The following section is specific to Flutter. 
# flutter pub get

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - assets/fonts/
    - assets/icons/

  
  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: Plus Jakarta
      fonts:
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Regular.otf
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Bold.otf
          weight: 700

    - family: Grandis Extended
      fonts:
        - asset: assets/fonts/grandis_extended/GrandisExtended-Regular.ttf
        - asset: assets/fonts/grandis_extended/GrandisExtended-Thin.ttf
          weight: 300
        - asset: assets/fonts/grandis_extended/GrandisExtended-Medium.ttf
          weight: 500
        - asset: assets/fonts/grandis_extended/GrandisExtended-Bold.ttf
          weight: 700
        - asset: assets/fonts/grandis_extended/GrandisExtended-Black.ttf
          weight: 900
